# Generated by Django 5.0.6 on 2024-05-09 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.TextField()),
                ('zip', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='resource-img')),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('file', models.FileField(upload_to='resource-file')),
                ('isPublished', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('readerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentsharing_app.reader')),
            ],
        ),
    ]
