# Generated by Django 5.0.6 on 2025-04-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="reader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=60)),
                ("password", models.TextField(blank=True, null=True)),
                ("zip", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="resource-img"),
                ),
                ("description", models.TextField()),
                ("link", models.TextField(blank=True, null=True)),
                (
                    "resfile",
                    models.FileField(blank=True, null=True, upload_to="resource-file"),
                ),
                ("isPublished", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "readerName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contentsharing_app.reader",
                    ),
                ),
            ],
        ),
    ]
